

dbt_projet_ventes:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server'  # (The ODBC Driver installed on your system)
      server: RUTH-STEPHANIE-
      database: Ventes_FTX
      schema: trans_actions
      windows_login: True
      trust_cert: True


 
